### ISSUE TITLE
The sorting (orderBy) is not working.

### ISSUE THREAD

**Issue by ranmeo** [tarreislam/laravel-redis-scout-engine#2]
Hi,

My "videos" table has "views" column with integer value. I have tried to search then order result by "views" but not working.

`$videos = Video::search($query)->orderBy('views', 'desc')->paginate(20)->withQueryString()`

I see function queryScoutModelsById in RedisScoutEngine has this part of code:

```
/*
         * Make sure the ordered result displays correctly
         */
        if (count($builder->orders) > 0) {
            $idsString = implode(',', $ids);
            foreach ($builder->orders as $order) {
                $query = $query->orderByRaw(sprintf("FIELD(%s, %s) %s", $model->getScoutKeyName(), $idsString, $order['direction']));
            }
        }
```

I changed 

` $query = $query->orderByRaw(sprintf("FIELD(%s, %s) %s", $model->getScoutKeyName(), $idsString, $order['direction']));`

to:

`$query = $query->orderBy($order['column'], $order['direction']);`

And it is working as the way I want it to.

So is there anything wrong with my usage?

Could you please me to check?

Thanks.

**Comment by tarreislam** [comment]
Hi, this is expected. The defalt sorting method is `SORT_NATURAL`

This means that this result

* 20 views
* 5000 views
* 1000 views
* 30 views

Would be sorted like this:

* 1000 views
* 20 views
* 30 views
* 5000 views

instead of

* 20
* 30 views
* 1000 views
* 5000 views


You can change it by chaning the `scout.php` config  from `SORT_NATURAL` to `SORT_REGULAR`

```php
    'redis' => [
       // ..... Other redis config
        |--------------------------------------------------------------------------
        | orderBy sort options
        |--------------------------------------------------------------------------
        |
        | Read more about sort options on PHPs official docs
        |
        | https://www.php.net/manual/en/function.sort.php
        */
        'sort_options' => SORT_NATURAL // <----- This decides the sorting
    ]

```

EDIT:

If you change that piece of code, you would run into problems when you more than 1 page, all sorting is done earlier in the code, the code you quoted just exists to ensure the searched results are correct
